import React from "react";
import { storiesOf } from "@storybook/react";
import Modal from ".";

const lorem = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vel orci a metus porttitor tincidunt. Vivamus eget dignissim nisi. Proin rhoncus massa tellus, in aliquet leo laoreet vel. In a feugiat ex. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed est ligula, luctus sed malesuada vel, volutpat a risus. Donec aliquam ligula semper magna dapibus, vitae porta erat semper. Integer feugiat ipsum sit amet fringilla mattis. Suspendisse sit amet sapien sit amet neque luctus maximus sit amet quis nulla. Duis venenatis eros eros. Suspendisse eu faucibus magna, non faucibus lectus. Phasellus lacus justo, faucibus eget libero in, tempor semper neque.

In ultrices, sem vitae luctus pharetra, dui dui euismod quam, non rutrum lorem tortor id nisi. Fusce pellentesque sapien non pellentesque lacinia. Nulla eget massa id lorem feugiat suscipit ac vitae nibh. Vestibulum ac ex eget tellus elementum tempor. Fusce ac odio vulputate quam suscipit dignissim. Duis eu mollis felis, sit amet consectetur neque. Fusce congue urna massa, vel lobortis odio rhoncus vel. Nulla quis lacus ac diam faucibus varius vitae non nunc. Quisque eleifend purus odio, pellentesque imperdiet orci molestie in. Ut consequat egestas ante, a mollis sem vestibulum a. Pellentesque quis lacinia sapien. Nullam et leo in massa eleifend convallis sit amet a sapien. Quisque nisl nunc, malesuada vel dui non, vestibulum gravida nibh. Duis malesuada egestas elit et eleifend. Fusce condimentum interdum tellus, id congue nibh viverra a. Cras ullamcorper blandit tincidunt.

Pellentesque dolor metus, ultrices eu augue ut, fringilla maximus dui. Ut commodo, nibh ut porta pellentesque, risus enim vulputate nisi, ac suscipit orci nulla ut ligula. Praesent nulla sapien, sodales nec molestie id, tincidunt ut ipsum. Donec malesuada lectus eu tempor laoreet. Cras felis libero, lobortis quis elit eu, egestas fermentum sapien. Sed blandit enim nulla, at hendrerit elit lacinia sed. Nulla ornare est id lorem placerat cursus. Curabitur faucibus felis dui, vitae vestibulum ligula cursus sed. Sed dignissim tincidunt elit a interdum. Quisque mattis nisl erat, sed fermentum felis molestie ultricies. Donec at diam nulla. Vestibulum vitae mauris quis ipsum cursus elementum. Phasellus eget nisi hendrerit, sollicitudin tellus a, venenatis leo.

Sed metus elit, auctor sed scelerisque vitae, egestas a nisl. Vivamus quis rutrum tortor, sit amet scelerisque dui. Morbi pretium urna vitae semper auctor. Praesent sit amet pellentesque orci, in mollis leo. Cras fermentum imperdiet massa at scelerisque. Ut non varius libero. Maecenas lectus quam, ultricies vitae laoreet nec, dignissim quis ipsum. Maecenas id ex cursus neque congue posuere non in nunc. Duis sodales ante justo, non dictum nisi sagittis eu. Donec eu iaculis mi. Proin imperdiet, lorem at viverra ornare, risus risus hendrerit tortor, ut elementum justo nulla vel mi. Nullam ut molestie magna. Mauris sit amet nulla molestie libero accumsan condimentum. Aenean ante tortor, gravida non ultrices et, dictum eget justo. Integer finibus, risus ac condimentum ultricies, velit ante volutpat risus, at fringilla enim ligula eget sem. Sed porttitor sapien nec faucibus ultrices.

Curabitur ut eleifend risus, vel molestie nisl. Nullam sed sapien lacinia, dictum justo sed, auctor tortor. Sed convallis orci risus, vel pharetra mi tristique sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam venenatis dui nibh, in mattis sapien aliquet quis. Nunc lorem magna, convallis et scelerisque in, porta in elit. Nulla ut diam magna. Mauris et erat quis elit suscipit dapibus eu ac tortor. Donec sit amet bibendum mi. Cras id lobortis ligula. In suscipit ultrices augue, eget venenatis turpis placerat sit amet. Etiam vitae efficitur neque.

Cras sodales commodo mi, vel blandit lorem tincidunt at. Suspendisse sagittis in est et tempor. Pellentesque dictum sapien non arcu rutrum, ac eleifend metus vestibulum. Cras interdum maximus massa, at ultricies ipsum molestie sit amet. Duis in mauris ornare arcu maximus pharetra. Nullam erat nibh, imperdiet at sollicitudin vitae, mollis non nulla. Fusce fermentum, dolor eget gravida hendrerit, elit metus lobortis enim, vel sagittis turpis massa et leo. Proin sed arcu sit amet risus ornare faucibus in tincidunt risus. Donec sodales metus quis dui vulputate lobortis. Maecenas felis augue, convallis et ultrices at, ullamcorper in ipsum. Curabitur pellentesque mollis efficitur. Cras quis laoreet justo.

Vestibulum iaculis vitae arcu non cursus. Pellentesque eu viverra orci, quis porta augue. Aenean tincidunt elit ligula, quis tincidunt felis blandit pellentesque. Morbi vel tellus facilisis, luctus orci sit amet, vulputate ligula. Nullam rutrum lorem vel nibh condimentum convallis. In sit amet ipsum eget libero porttitor tempor id eu lectus. Sed sed condimentum odio. Proin sollicitudin ipsum eu suscipit elementum. Vestibulum rhoncus ultricies auctor. Maecenas mollis egestas nunc sed accumsan. Morbi sit amet lorem vel massa tempus interdum vitae ac tellus.

Duis mollis augue orci, id faucibus arcu accumsan a. Mauris vitae velit augue. Quisque ut ante ac neque condimentum lobortis. Maecenas ac tortor ornare, elementum tortor eu, sodales enim. Sed et ornare orci, a iaculis ex. Aliquam bibendum quis sapien sollicitudin blandit. Aenean efficitur imperdiet quam at congue. Proin aliquam enim quis arcu maximus finibus. Proin et semper sem, sit amet dapibus mi. Donec consectetur, lectus nec molestie venenatis, ipsum odio pharetra ipsum, ac ultricies velit leo rutrum est. Nulla cursus quis velit non euismod. Ut sit amet erat viverra, posuere tortor in, mollis urna. Aliquam erat volutpat. Cras id magna placerat purus viverra tristique vel sit amet enim. Donec vel massa sed quam feugiat bibendum. Duis a porta sapien, sed ornare augue.

Sed luctus pulvinar ullamcorper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla id lorem dui. Curabitur nulla neque, varius ut ipsum eu, scelerisque cursus odio. Aenean augue mauris, sagittis eu scelerisque eget, gravida in velit. Nulla facilisi. Proin vel sagittis justo. Phasellus egestas enim nisi, at elementum augue gravida in. Curabitur sodales nibh vel urna elementum, ut volutpat magna condimentum. Vestibulum vulputate magna nibh. Sed feugiat vel leo vel faucibus. Ut efficitur finibus nisl sed placerat. Nam euismod turpis sagittis augue iaculis efficitur. Vestibulum feugiat pellentesque urna et iaculis. Nam congue tempus gravida. Phasellus mauris eros, fringilla sit amet diam at, vestibulum convallis odio.

Quisque nec est eros. In felis urna, egestas nec fermentum nec, consectetur a enim. Quisque sapien eros, sollicitudin at aliquet sed, rutrum in leo. Vivamus malesuada, purus sed porta ultrices, tellus nunc maximus sapien, vitae scelerisque odio turpis et nulla. Aliquam in rutrum magna. Donec magna arcu, commodo vitae scelerisque quis, rutrum quis quam. Fusce semper luctus scelerisque. Curabitur gravida mauris sed mollis ullamcorper. Cras nunc erat, pharetra quis velit a, volutpat vulputate nisi. Praesent urna lorem, interdum ut velit ac, gravida luctus nunc. In a eros vehicula, rhoncus lorem id, molestie dolor.
`;

storiesOf("Modal", module).add("Default", () => (
  <Modal hasHeader hasFooter description={lorem} />
));
